controllers/TgstepController.php
<?php
namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use app\models\Tgstep;
use yii\filters\VerbFilter;
use yii\web\ConflictHttpException;
use yii\web\NotFoundHttpException;
use yii\helpers\Json;
use yii\helpers\ArrayHelper;
use yii\web\Response;
use app\models\Modelhistory;


class TgstepController extends Controller
{

  public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /*
    public function beforeAction($action) {
      if(Yii::$app->user->isGuest) {
        return $this->redirect(Yii::$app->user->loginUrl);
      } else {
        return true;
      }
    } */

    public function actionGetTree () {
      Yii::$app->response->format = Response::FORMAT_JSON;
      $query = Tgstep::find()->where(['is_deleted'=>false])->orderBy([
        'parent_id'=>SORT_ASC, 'position'=>SORT_ASC]);
      if (null === $rows = $query->asArray()->all()) {
        return [];
      }

      $result = [];

      foreach ($rows as $row) {
        $parent = ArrayHelper::getValue($row, 'parent_id', 0);
        $item = [
          'id' => ArrayHelper::getValue($row, 'id', 0),
          'parent' => ($parent) ? $parent : '#',
          'text' => ArrayHelper::getValue($row, 'step_name', 'item'),
          'a_attr' => [
            'data-id' => ArrayHelper::getValue($row, 'id', 0),//$row['id'],
            'data-parent_id' => ArrayHelper::getValue($row, 'parent_id', 0)//$row['parent_id']
          ],
        ];
        $result[$row['id']] = $item;
      }

      Yii::$app->response->format = Response::FORMAT_RAW;
      header('Content-Type: application/json');
      return json_encode(array_values($result));
    }
    /**
     * Lists all Tree models.*
     * @return mixed
     */
    public function actionIndex()
    {
        $id = Yii::$app->request->get('id');
        $initial = Tgstep::findOne($id);
        $query = Tgstep::find()->where(['is_deleted'=>false])->orderBy([
          'parent_id'=>SORT_ASC, 'position'=>SORT_ASC]);
          $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
            'sort' => [
              'defaultOrder' => [
                'parent_id' => SORT_ASC,
                'position' => SORT_ASC,
              ]
            ],
          ]);

          return $this->render('index', [
            'dataProvider' => $dataProvider,
            'initial' => $initial,
            'buttonTemplate' => (Yii::$app->user->identity->isAdmin) ?
              '{view}{update}{zoomin}{add}{move}' : '{view}{update}{zoomin}',
          ]);
    }

/*
    public function actionKaIndex() {
        $tree = new \kasoft\jstree\JsTree([
            'modelName' => 'Tgstep',    // * Namespace of the Model
            'modelPropertyId' => 'id',                       // * primary Key
            'modelPropertyParentId' => 'parent_id',          // * Parent ID for tree items
            'modelPropertyPosition' => 'position',          // *for sorting items
            'modelPropertyName' => 'step_name',                  // * Fieldname to show
            'modelFirstParentId' => NULL,                   // * ID for the Tree to start
            'modelPropertyType' => 'type',                  // Item type (for Icon and jsTree rights)
            'controllerId' => 'ka-index',                      // Controler Actions which should handle everything
            'jstreeDiv' => '#jstree',                       // DIV where the Tree will be displayed
            'jstreeIcons' => false,                         // Show Icons or not
            'jstreePlugins' => ["contextmenu", "dnd"],   // Plugins to be load
            'jstreeType' => [                               // jsTree Type Options
                "#" => [
                    "max_children" => -1,
                    "max_depth" => -1,
                    "valid_children" => -1,
                    "icon" => "glyphicon glyphicon-th-list"
                ],
                "default" => [
                    "icon" => "glyphicon glyphicon-question-sign"
                ],
            ]
        ]);

        return $this->render('ka-index');
    } */

    public function actionView($id)
    {
        return $this->render('view', [
          'model' => $this->findModel($id),
        ]);
    }

    public function actionTreeIndex()
    {
      return $this-> render('treeview');
    }

    /* show history of the model with $id */
    public function actionHistory($id)
    {
      $query = Modelhistory::find()->where([
        'table'=> 'dbtl_steps', 'field_id'=>$id]);

      $dataProvider = new ActiveDataProvider([
        'query' => $query]);

      return $this->render('history', [
        'model_id' => $id,
        'dataProvider' => $dataProvider,
      ]);
    }

    /* show recent changes in the table */
    public function actionChanges()
    {
      $query = Modelhistory::find()->where([
        'table'=> 'dbtl_steps']);

      $dataProvider = new ActiveDataProvider([
        'query' => $query,
        'sort' => [
          'defaultOrder' => [
            'date' => SORT_DESC,
          ]
        ],
      ]);

      return $this->render('changes', [
        'dataProvider' => $dataProvider,
      ]);
    }

    public function actionCreate()
    {
      $model = new Tgstep();

      if ($model->load(Yii::$app->request->post()))
      {
        if($model->parent_id == null)
        {
          $model->parent_id = 0;
        }
        $model->position = 1 + Tgstep::countChildren($model->parent_id);
        $model->save();
        return $this->redirect(['view', 'id' => $model->id]);
      }
      else
      {
        return $this->render('create', [
          'model' => $model,
        ]);
      }
    }

    public function actionZoomin($id)
    {
      $branch_ids = Tgstep::getBranch($id);
      //var_dump($branch_ids);
      $query = Tgstep::find(['is_deleted'=>false])->where([
        'id'=>$branch_ids])->orderBy([
          'parent_id'=>SORT_ASC, 'position'=>SORT_ASC]);
      $model = $this->findModel($id);
      $dataProvider = new ActiveDataProvider([
          'query' => $query,
          'pagination' => false,
          'sort' => [
            'defaultOrder' => [
              'parent_id' => SORT_ASC,
              'position' => SORT_ASC,
            ]
          ],
      ]);

        return $this->render('zoom', [
            'dataProvider' => $dataProvider,
            'root_id' => $model->parent_id,
        ]);
    }

    public function actionZoomout($id)
    {
      $model = $this->findModel($id);
      $branch_ids = Tgstep::getBranch($model->parent_id);
      //var_dump($branch_ids);
      $query = Tgstep::find(['is_deleted'=>false])->where([
        'id'=>$branch_ids])->orderBy([
          'parent_id'=>SORT_ASC, 'position'=>SORT_ASC]);
      $dataProvider = new ActiveDataProvider([
          'query' => $query,
          'pagination' => false,
          'sort' => [
            'defaultOrder' => [
              'parent_id' => SORT_ASC,
              'position' => SORT_ASC,
            ]
          ],
      ]);

      $parent_model = $this->findModel($model->parent_id);
        return $this->render('zoom', [
            'dataProvider' => $dataProvider,
            'root_id' => $parent_model->parent_id,
        ]);
    }

    /* actionMove needs to be finalized. Concurrency issues need to be checked */
    public function actionMove($id) {
      $model = $this->findModel($id);
      $old_parent_id = $model->parent_id;

      try {
        if ($model->load(Yii::$app->request->post())) {

          $transaction = Yii::$app->db->beginTransaction();

          // Determine the new parent id
          if($model->before_or_after == 'in') {
            // If "in", then we know that $move_to_target is the new parent_id
            $new_parent_id = $model->move_to_target;
            $model->position = 1 + Tgstep::countChildren($new_parent_id);
          } else {
            // If "before" or "after", note that $move_to_target is a sibling model
            // Therefore, new parent id would be $move_to_target->parent_id
            $sibling_model = $this->findModel($model->move_to_target);
            $new_parent_id = $sibling_model->parent_id;

            // Note: getChildren sorts children in the order of position
            $all_siblings_ids = Tgstep::getChildren($new_parent_id);
            // what if $model->id is among $all_siblings_ids?
            $all_siblings_ids = array_diff($all_siblings_ids, [$model->id=>$model->id]);

            // Note the position where $model should to be inserted.
            // Here we are just noting the position, The insertion comes a few lines
            // later.
              $insert_at = $sibling_model->position;

            // In the scenario that you want to move the $model's position
            // under the same parent (i.e. without changing it to a new
            // it's parent), you need to make and adjustment to the $insert_at
            // if $model->position is before $sibling_model->position.
            // This is because, when you move $model down from its position,
            // you vacate one spot before $sibling_model->position.

            if(($old_parent_id == $new_parent_id) and (
              $model->position < $sibling_model->position)) {
                $insert_at = $insert_at - 1;
            }

            // The actual moving takes place here. To make sure that
            // the positions are indexed from 1 to countChildren($new_parent_id)
            // you need $this_child_pos.
            ///
            $this_child_pos = 0;
            foreach ($all_siblings_ids as $a_sibling_id) {
              $a_sibling_model = $this->findModel($a_sibling_id);

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            //['label' => 'Home', 'url' => ['/site/index']],
            // ['label' => 'About', 'url' => ['/site/about']],
            //['label' => 'DBTL Tasks', 'url' => ['/dbtl/index']],
            //['label' => 'DBTL Tasks', 'url' => (Yii::$app->user->isGuest) ? ['/user/security/login'] : ['/tgstep/index']],
            // ['label' => 'Contact', 'url' => ['/site/contact']],

            (Yii::$app->user->isGuest) ? ['label' => ''] :
            [
              'label' => 'DBTL Tasks',
              'items' => [
                ['label' => "Grid View", 'url' => ['/tgstep/index']],
                ['label' => "Tree View", 'url' => ['/tgstep/tree-index']],
                ['label' => "Recent changes", 'url' => ['/tgstep/changes']],
              ],
            ],
            (Yii::$app->user->isGuest) ?
            [
              'label' => 'Login',
              'items' => [
                  ['label' => 'Login', 'url' => ['/user/security/login']],
                  ['label' => 'Register', 'url' => ['/user/registration/register']],
              ],
            ] :
            [
              'label' => Yii::$app->user->identity->username,
              'items' => [
                [
                  'label' => 'Logout', 'url' => ['/user/security/logout'],
                  'linkOptions' => ['data-method' => 'post'],
                ],
              ],

            ],
            /*
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
            */
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; VTT / EU-IBISBA<?= date('Y') ?></p>

        <p class="pull-right">Contact: EU-IBISBA WP6</p> <!-- < ?= Yii::powered() ? ></p> -->
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>