models/Tgstep.php
<?php
namespace app\models;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use \yii2tech\ar\softdelete\SoftDeleteBehavior;

/**
 * @property string $description
 * @property integer $parent_id
 */
class Tgstep extends ActiveRecord
{
  //public $new_parent_id;
  //public $sibling_id;
  public $before_or_after;
  public $move_to_target;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dbtl_steps';
    }

    public function attributeLabels()
    {
      return [
        'step_desc' => 'Description',
      ];
    }

    public function behaviors()
    {
      return [
        'softDeleteBehavior' => [
          'class' => SoftDeleteBehavior::className(),
          'softDeleteAttributeValues' => [
            'is_deleted' => true
          ],
        ],
        'history' => [
          'class' => \nhkey\arh\ActiveRecordHistoryBehavior::className(),
          'manager' => '\nhkey\arh\managers\DBManager',
          'ignoreFields' => ['is_deleted', 'version', 'created', 'last_modified'],
        ],
      ];
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['before_or_after'], 'string'],
            [['before_or_after'], 'trim'],
            [['before_or_after'], 'in',
              'range'=>['before', 'after', 'in'],
              'message'=>'Choose one of before, after, or in'],
            [['move_to_target'], 'integer'],
            [['step_name'], 'required'],
            [['step_name'], 'string', 'max'=>250],
            [['step_name'], 'trim'],
            [['step_desc'], 'safe'],
            [['step_desc'], 'string', 'max'=>500],
            [['step_desc'], 'trim'],
            [['responsible_partner'], 'safe'],
            [['responsible_partner'], 'string', 'max'=>50],
            [['responsible_partner'], 'trim'],
            [['organism'], 'safe'],
            [['organism'], 'string', 'max'=>50],
            [['organism'], 'trim'],
            [['part_of_service'], 'safe'],
            [['part_of_service'], 'string', 'max'=>50],
            [['part_of_service'], 'trim'],
            [['duration_in_days'], 'safe'],
            [['duration_in_days'], 'number'],
            [['success_rate'], 'safe'],
            [['success_rate'], 'number', 'min'=>0, 'max'=>1],
            [['sop_url'], 'safe'],
            [['sop_url'], 'string', 'max'=>1000],
            [['sop_url'], 'trim'],
            [['comments'], 'safe'],
            [['comments'], 'string', 'max'=>1000],
            [['comments'], 'trim'],
            [['parent_id'], 'integer'],
            [['version'], 'integer'],
            [['version'], 'default', 'value'=>0],
            [['created', 'last_modified'], 'safe'],
        ];
    }

    public function optimisticLock() {
      return 'version';
    }

    public function countChildren($id)
    {
      /* the number of elements with id as the parent_id
       * gives the number of children of parent_id */
      return self::find()->where(['parent_id'=>$id])->count();
    }

    public function getChildren($id)
    {
      /* the ids of elements with parent_id = $id */
      return ArrayHelper::map(
          self::find()->select('id')->where([
            'is_deleted'=>false,'parent_id'=>$id])->orderBy([
            'position' => SORT_ASC])->all(),
            'id', 'id');
    }

    /*
    public function getChildrenNames($id)
    {
      return ArrayHelper::map(
          self::find()->select('id','step_name')->where([
            'is_deleted'=>false,'parent_id'=>$id])->all(),
            'id', 'step_name');
    } */
    /* Get the ids of this element and all other elements under this branch */
    public function getBranch($id) {
      $lineage_ids = [(int)$id=>(int)$id];
      do {
        // it is really important to create an associative array (map)
        // due to the PHP's exceptional behavior of array_merge in the next step
        $children_ids = ArrayHelper::map(
          self::find()->select('id')->where(['is_deleted'=>false,'parent_id'=>$id])->all(),
          'id', 'id');
        $lineage_ids = $lineage_ids + $children_ids;
        $id = $children_ids;
      } while($id);
      return $lineage_ids;
    }
}
?>

controllers/TgstepController.php
<?php
namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use app\models\Tgstep;
use yii\filters\VerbFilter;
use yii\web\ConflictHttpException;
use yii\web\NotFoundHttpException;
use yii\helpers\Json;
use yii\helpers\ArrayHelper;
use yii\web\Response;
use app\models\Modelhistory;


class TgstepController extends Controller
{

  public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /*
    public function beforeAction($action) {
      if(Yii::$app->user->isGuest) {
        return $this->redirect(Yii::$app->user->loginUrl);
      } else {
        return true;
      }
    } */

    public function actionGetTree () {
      Yii::$app->response->format = Response::FORMAT_JSON;
      $query = Tgstep::find()->where(['is_deleted'=>false])->orderBy([
        'parent_id'=>SORT_ASC, 'position'=>SORT_ASC]);
      if (null === $rows = $query->asArray()->all()) {
        return [];
      }

      $result = [];

      foreach ($rows as $row) {
        $parent = ArrayHelper::getValue($row, 'parent_id', 0);
        $item = [
          'id' => ArrayHelper::getValue($row, 'id', 0),
          'parent' => ($parent) ? $parent : '#',
          'text' => ArrayHelper::getValue($row, 'step_name', 'item'),
          'a_attr' => [
            'data-id' => ArrayHelper::getValue($row, 'id', 0),//$row['id'],
            'data-parent_id' => ArrayHelper::getValue($row, 'parent_id', 0)//$row['parent_id']
          ],
        ];
        $result[$row['id']] = $item;
      }

      Yii::$app->response->format = Response::FORMAT_RAW;
      header('Content-Type: application/json');
      return json_encode(array_values($result));
    }
    /**
     * Lists all Tree models.*
     * @return mixed
     */
    public function actionIndex()
    {
        $id = Yii::$app->request->get('id');
        $initial = Tgstep::findOne($id);
        $query = Tgstep::find()->where(['is_deleted'=>false])->orderBy([
          'parent_id'=>SORT_ASC, 'position'=>SORT_ASC]);
          $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
            'sort' => [
              'defaultOrder' => [
                'parent_id' => SORT_ASC,
                'position' => SORT_ASC,
              ]
            ],
          ]);

          return $this->render('index', [
            'dataProvider' => $dataProvider,
            'initial' => $initial,
            'buttonTemplate' => (Yii::$app->user->identity->isAdmin) ?
              '{view}{update}{zoomin}{add}{move}' : '{view}{update}{zoomin}',
          ]);
    }

/*
    public function actionKaIndex() {
        $tree = new \kasoft\jstree\JsTree([
            'modelName' => 'Tgstep',    // * Namespace of the Model
            'modelPropertyId' => 'id',                       // * primary Key
            'modelPropertyParentId' => 'parent_id',          // * Parent ID for tree items
            'modelPropertyPosition' => 'position',          // *for sorting items
            'modelPropertyName' => 'step_name',                  // * Fieldname to show
            'modelFirstParentId' => NULL,                   // * ID for the Tree to start
            'modelPropertyType' => 'type',                  // Item type (for Icon and jsTree rights)
            'controllerId' => 'ka-index',                      // Controler Actions which should handle everything
            'jstreeDiv' => '#jstree',                       // DIV where the Tree will be displayed
            'jstreeIcons' => false,                         // Show Icons or not
            'jstreePlugins' => ["contextmenu", "dnd"],   // Plugins to be load
            'jstreeType' => [                               // jsTree Type Options
                "#" => [
                    "max_children" => -1,
                    "max_depth" => -1,
                    "valid_children" => -1,
                    "icon" => "glyphicon glyphicon-th-list"
                ],
                "default" => [
                    "icon" => "glyphicon glyphicon-question-sign"
                ],
            ]
        ]);

        return $this->render('ka-index');
    } */

    public function actionView($id)
    {
        return $this->render('view', [
          'model' => $this->findModel($id),
        ]);
    }

    public function actionTreeIndex()
    {
      return $this-> render('treeview');
    }

    /* show history of the model with $id */
    public function actionHistory($id)
    {
      $query = Modelhistory::find()->where([
        'table'=> 'dbtl_steps', 'field_id'=>$id]);

      $dataProvider = new ActiveDataProvider([
        'query' => $query]);

      return $this->render('history', [
        'model_id' => $id,
        'dataProvider' => $dataProvider,
      ]);
    }

    /* show recent changes in the table */
    public function actionChanges()
    {
      $query = Modelhistory::find()->where([
        'table'=> 'dbtl_steps']);

      $dataProvider = new ActiveDataProvider([
        'query' => $query,
        'sort' => [
          'defaultOrder' => [
            'date' => SORT_DESC,
          ]
        ],
      ]);

      return $this->render('changes', [
        'dataProvider' => $dataProvider,
      ]);
    }

    public function actionCreate()
    {
      $model = new Tgstep();

      if ($model->load(Yii::$app->request->post()))
      {
        if($model->parent_id == null)
        {
          $model->parent_id = 0;
        }
        $model->position = 1 + Tgstep::countChildren($model->parent_id);
        $model->save();
        return $this->redirect(['view', 'id' => $model->id]);
      }
      else
      {
        return $this->render('create', [
          'model' => $model,
        ]);
      }
    }

    public function actionZoomin($id)
    {
      $branch_ids = Tgstep::getBranch($id);
      //var_dump($branch_ids);
      $query = Tgstep::find(['is_deleted'=>false])->where([
        'id'=>$branch_ids])->orderBy([
          'parent_id'=>SORT_ASC, 'position'=>SORT_ASC]);
      $model = $this->findModel($id);
      $dataProvider = new ActiveDataProvider([
          'query' => $query,
          'pagination' => false,
          'sort' => [
            'defaultOrder' => [
              'parent_id' => SORT_ASC,
              'position' => SORT_ASC,
            ]
          ],
      ]);

        return $this->render('zoom', [
            'dataProvider' => $dataProvider,
            'root_id' => $model->parent_id,
        ]);
    }

    public function actionZoomout($id)
    {
      $model = $this->findModel($id);
      $branch_ids = Tgstep::getBranch($model->parent_id);
      //var_dump($branch_ids);
      $query = Tgstep::find(['is_deleted'=>false])->where([
        'id'=>$branch_ids])->orderBy([
          'parent_id'=>SORT_ASC, 'position'=>SORT_ASC]);
      $dataProvider = new ActiveDataProvider([
          'query' => $query,
          'pagination' => false,
          'sort' => [
            'defaultOrder' => [
              'parent_id' => SORT_ASC,
              'position' => SORT_ASC,
            ]
          ],
      ]);

      $parent_model = $this->findModel($model->parent_id);
        return $this->render('zoom', [
            'dataProvider' => $dataProvider,
            'root_id' => $parent_model->parent_id,
        ]);
    }

    /* actionMove needs to be finalized. Concurrency issues need to be checked */
    public function actionMove($id) {
      $model = $this->findModel($id);
      $old_parent_id = $model->parent_id;

      try {
        if ($model->load(Yii::$app->request->post())) {

          $transaction = Yii::$app->db->beginTransaction();

          // Determine the new parent id
          if($model->before_or_after == 'in') {
            // If "in", then we know that $move_to_target is the new parent_id
            $new_parent_id = $model->move_to_target;
            $model->position = 1 + Tgstep::countChildren($new_parent_id);
          } else {
            // If "before" or "after", note that $move_to_target is a sibling model
            // Therefore, new parent id would be $move_to_target->parent_id
            $sibling_model = $this->findModel($model->move_to_target);
            $new_parent_id = $sibling_model->parent_id;

            // Note: getChildren sorts children in the order of position
            $all_siblings_ids = Tgstep::getChildren($new_parent_id);
            // what if $model->id is among $all_siblings_ids?
            $all_siblings_ids = array_diff($all_siblings_ids, [$model->id=>$model->id]);

            // Note the position where $model should to be inserted.
            // Here we are just noting the position, The insertion comes a few lines
            // later.
              $insert_at = $sibling_model->position;

            // In the scenario that you want to move the $model's position
            // under the same parent (i.e. without changing it to a new
            // it's parent), you need to make and adjustment to the $insert_at
            // if $model->position is before $sibling_model->position.
            // This is because, when you move $model down from its position,
            // you vacate one spot before $sibling_model->position.

            if(($old_parent_id == $new_parent_id) and (
              $model->position < $sibling_model->position)) {
                $insert_at = $insert_at - 1;
            }

            // The actual moving takes place here. To make sure that
            // the positions are indexed from 1 to countChildren($new_parent_id)
            // you need $this_child_pos.
            ///
            $this_child_pos = 0;
            foreach ($all_siblings_ids as $a_sibling_id) {
              $a_sibling_model = $this->findModel($a_sibling_id);

views/tgstep/_search.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\MouldsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tgstep-search">

  <?php $form = ActiveForm::begin([
    'layout' => 'inline',
    'action' => ['index'],
    'method' => 'get',
  ]); ?>

  <!-- <div class="form-group"> -->
  <div class="input-group">
    <?= $form->field($model, 'search_keyword')->textInput([
      'placeholder'=>'Type a keyword to search DBTL steps table'])
      ->label(false) ?>
    <span class="input-group-btn">
      <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
    </span>
  </div>

  <?= Html::a('Reset search filters', ['index'], ['class' => 'btn btn-default']) ?>
    <!-- </div> -->

  <?php ActiveForm::end(); ?>

</div>

views/tgstep/changes.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

$this->title = 'TasCu: recent changes and additions';
$this->params['breadcrumbs'][] = ['label' => 'Index', 'url' => 'index'];
$this->params['breadcrumbs'][] = 'Changes';
?>
<div class="record-history">

<?php Pjax::begin(); ?>
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'tableOptions' => ['class' => 'table-striped table-condensed table-hover table-bordered'],
        'headerRowOptions' => ['class' => 'breadcrumb'],
        'columns' => [
            //'table',
            [
              'attribute' => 'field_id',
              'format' => 'raw',
              'value' => function($data) {
                return Html::a($data->field_id, ['tgstep/view', 'id' => $data->field_id], ['data-pjax' => 0]);
              }
            ],
            'field_id',
            'field_name',
            'old_value',
            'new_value',
            'date',
            //'type',
            'user_id'
        ],
    ]); ?>
  </div>
<?php Pjax::end(); ?>

views/tgstep/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Moclo */

$this->title = 'TasCu: create DBTL step';
$this->params['breadcrumbs'][] = ['label' => 'Index', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Create';
?>
<div class="tgstep-create">

    <h1><?= Html::encode('Create DBTL step') ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/tgstep/history.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

$this->title = 'TasCu: edit history of DBTL step '.$model_id;
$this->params['breadcrumbs'][] = ['label' => 'Index', 'url' => 'index'];
$this->params['breadcrumbs'][] = ['label' => $model_id, 'url' => ['view', 'id' => $model_id]];
$this->params['breadcrumbs'][] = 'History';
?>
<div class="record-history">

<?php Pjax::begin(); ?>
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'tableOptions' => ['class' => 'table-striped table-condensed table-hover table-bordered'],
        'headerRowOptions' => ['class' => 'breadcrumb'],
        'columns' => [
            //'table',
            [
              'attribute' => 'field_id',
              'format' => 'raw',
              'value' => function($data) {
                return Html::a($data->field_id, ['tgstep/view', 'id' => $data->field_id], ['data-pjax' => 0]);
              }
            ],
            //'field_id',
            'field_name',
            'old_value',
            'new_value',
            'date',
            //'type',
            'user_id'
        ],
    ]); ?>
  </div>
<?php Pjax::end(); ?>

views/tgstep/index.php
<?php
use leandrogehlen\treegrid\TreeGrid;
use yii\helpers\Html;
use yii\helpers\Url;
use Yii;

$this->title = 'TasCu: DBTL Index';
$this->params['breadcrumbs'][] = ['label' => 'Index', 'url' => ['index']];
?>

<div class="form-group">
  <?php /* echo Html::a('Create DBTL step', ['create'],
    [
      'class' => 'btn btn-success',
      'style'=>'float:right;'
      //'style'=>'width:100%;margin-top:1em;margin-bottom:1em;'
    ]) */ ?>

  <?php //echo $this->render('_search', ['model' => $searchModel]); ?>
</div>
<?php
echo dkhlystov\widgets\TreeGrid::widget([
  'dataProvider' => $dataProvider,
  'initialNode' => $initial,
  'showRoots' => true,

  /* These pluginOptions don't work, but are there begging to be debugged */
  'pluginOptions' => [
    'saveState' => 'true',
    'saveStateMethod' => 'cookie',
    //'style' => 'table-layout:inherit;'
  ],
  'columns' => [
    [
      'attribute' => 'step_name',
      'headerOptions' => ['style' => 'width:60%;'],
    ],
    [
      'attribute' => 'step_desc',
      'headerOptions' => ['style' => 'width:20%;'],
    ],
    //'responsible_partner',
/*
    [
      'attribute' => 'comments',
      'headerOptions' => ['style' => 'width:20%;'],
    ], */
    [
      'attribute' => 'sop_url',
      'headerOptions' => ['style' => 'width:10%;'],

    ],
    [
      'class' => 'yii\grid\ActionColumn',
      'headerOptions' => ['style' => 'width:10%;'],

      'template' => $buttonTemplate,
      #'template' => (Yii::$app->user->identity->isAdmin) ? '{view}{update}{zoomin}{add}{move}' : '{view}{update}{zoomin}',
      #'template' => (Yii::$app->user->can('admin')) ? '{view}{update}{zoomin}{add}{move}' : '{view}{update}{zoomin}',
      'buttons' => [
        'zoomin' => function ($url) {
          return Html::a(
            '<span class="glyphicon glyphicon-zoom-in"></span>',
            $url,
            [
              'title' => 'zoomin',
              'data-pjax' => '0',
            ]
          );
        },
        'add' => function ($url) {
          return Html::a(
            '<span class="glyphicon glyphicon-plus"></span>',
            $url,
            [
              'title' => 'addChild',
              'data-pjax' => '0',
            ]
          );
        },
        'move' => function ($url) {
          return Html::a(
            '<span class="glyphicon glyphicon-move"></span>',
            $url,
            [
              'title' => 'move',
              'data-pjax' => '0',
            ]
          );
        },
      ],
      'urlCreator' => function ($action, $model, $key, $index) {
        if ($action === 'zoomin') {
          $url = Url::toRoute(['tgstep/zoomin', 'id' => $model->id]);
          return $url;
        } elseif ($action === 'add') {
          $url = Url::toRoute(['tgstep/add', 'id' => $model->id]);
          return $url;
        } elseif ($action === 'view') {
          $url = Url::toRoute(['tgstep/view', 'id' => $model->id]);
          return $url;
        } elseif ($action === 'update') {
          $url = Url::toRoute(['tgstep/update', 'id' => $model->id]);
          return $url;
        } elseif ($action === 'delete') {
          $url = Url::toRoute(['tgstep/delete', 'id' => $model->id]);
          return $url;
        } elseif ($action === 'move') {
          $url = Url::toRoute(['tgstep/move', 'id' => $model->id]);
          return $url;
        }
      }
    ],
  ]
]);
?>

views/tgstep/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Moclo */

$this->title = 'TasCu: update DBTL step: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Index', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="tgstep-update">

    <h1><?= Html::encode('Update DBTL step '.$model->id) ?></h1>
    <h2><?= Html::encode($model->step_name) ?></h2>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/tgstep/zoom.php
<?php
use leandrogehlen\treegrid\TreeGrid;
use yii\helpers\Html;
use yii\helpers\Url;
?>

<div class="form-group">
  <?php /* echo Html::a('Create DBTL step', ['create'],
    [
      'class' => 'btn btn-success',
      'style'=>'float:right;'
      //'style'=>'width:100%;margin-top:1em;margin-bottom:1em;'
    ]) */ ?>

  <?php //echo $this->render('_search', ['model' => $searchModel]); ?>
</div>
<?php
echo dkhlystov\widgets\TreeGrid::widget([
  'dataProvider' => $dataProvider,
  'showRoots' => true,
  'rootParentId' => $root_id,

  'columns' => [
    [
      'attribute' => 'step_name',
      'headerOptions' => ['style' => 'width:60%;'],
      ],
			[
        'attribute' => 'step_desc',
        'headerOptions' => ['style' => 'width:10%;'],
      ],
      //'responsible_partner',
    /*  [
        'attribute' => 'comments',
        'headerOptions' => ['style' => 'width:20%;'],
      ], */
    [
      'attribute' => 'sop_url',
      'headerOptions' => ['style' => 'width:10%;'],

    ],
      [
        'class' => 'yii\grid\ActionColumn',
        'headerOptions' => ['style' => 'width:10%;'],
        #'template' => '{view}{update}{zoomin}{zoomout}{add}{move}',
        'template' => (Yii::$app->user->identity->isAdmin) ? '{view}{update}{zoomin}{zoomout}{add}{move}' : '{view}{update}{zoomin}{zoomout}',
        'buttons' => [
          'zoomin' => function ($url) {
            return Html::a(
              '<span class="glyphicon glyphicon-zoom-in"></span>',
              $url,
              [
                'title' => 'zoomin',
                'data-pjax' => '0',
              ]
            );
          },
          'zoomout' => function ($url) {
            return Html::a(
              '<span class="glyphicon glyphicon-zoom-out"></span>',
              $url,
              [
                'title' => 'zoomout',
                'data-pjax' => '0',
              ]
            );
          },
          'add' => function ($url) {
            return Html::a(
              '<span class="glyphicon glyphicon-plus"></span>',
              $url,
              [
                'title' => 'addChild',
                'data-pjax' => '0',
              ]
            );
          },
          'move' => function ($url) {
            return Html::a(
              '<span class="glyphicon glyphicon-move"></span>',
              $url,
              [
                'title' => 'move',
                'data-pjax' => '0',
              ]
            );
          },
        ],

        'urlCreator' => function ($action, $model, $key, $index) {
          if ($action === 'zoomin') {
            $url = Url::toRoute(['tgstep/zoomin', 'id' => $model->id]);
            return $url;
          } elseif ($action === 'zoomout') {
            if($model->parent_id == 0) {
              $url = Url::toRoute(['tgstep/index']);
            } else {
              $url = Url::toRoute(['tgstep/zoomout', 'id' => $model->id]);
            }
            return $url;
          } elseif ($action === 'add') {
            $url = Url::toRoute(['tgstep/add', 'id' => $model->id]);
            return $url;
          } elseif ($action === 'view') {
            $url = Url::toRoute(['tgstep/view', 'id' => $model->id]);
            return $url;
          } elseif ($action === 'update') {
            $url = Url::toRoute(['tgstep/update', 'id' => $model->id]);
            return $url;
          } /* elseif ($action === 'delete') {
            $url = Url::toRoute(['tgstep/delete', 'id' => $model->id]);
            return $url;
          } */ elseif ($action === 'move') {
          $url = Url::toRoute(['tgstep/move', 'id' => $model->id]);
          return $url;
        }
      }
    ],
  ]
]);
/*
echo TreeGrid::widget([
    'dataProvider' => $dataProvider,
    'keyColumnName' => 'id',
    'parentColumnName' => 'parent_id',
    'parentRootValue' => $root_id, //first parentId value
    'pluginOptions' => [
      // For zoom-in and zoom-out to work, the initialState must be 'expanded'
        'initialState' => 'expanded',
        'expanderExpandedClass' => 'glyphicon glyphicon-chevron-down',
        'expanderCollapsedClass' => 'glyphicon glyphicon-chevron-right',
    ],
    'columns' => [
      //'parent_id',
      'step_name',
      'responsible_partner',
      'sop_url',
      //'step_desc',
      'comments',
      [
        'class' => 'yii\grid\ActionColumn',
        'template' => '{view}{update}{delete}{zoomin}{zoomout}{add}',
        'buttons' => [
          'zoomin' => function ($url) {
            return Html::a(
              '<span class="glyphicon glyphicon-zoom-in"></span>',
              $url,
              [
                'title' => 'zoomin',
                'data-pjax' => '0',
              ]
            );
          },
          'zoomout' => function ($url) {
            return Html::a(
              '<span class="glyphicon glyphicon-zoom-out"></span>',
              $url,
              [
                'title' => 'zoomout',
                'data-pjax' => '0',
              ]
            );
          },
          'add' => function ($url) {
            return Html::a(
              '<span class="glyphicon glyphicon-plus"></span>',
              $url,
              [
                'title' => 'addChild',
                'data-pjax' => '0',
              ]
            );
          },
        ],
        'urlCreator' => function ($action, $model, $key, $index) {
          if ($action === 'zoomin') {
            $url = Url::toRoute(['tgstep/zoomin', 'id' => $model->id]);
            return $url;
          } elseif ($action === 'zoomout') {
            if($model->parent_id == 0) {
              $url = Url::toRoute(['tgstep/index']);
            } else {
              $url = Url::toRoute(['tgstep/zoomout', 'id' => $model->id]);
            }
            return $url;
          } elseif ($action === 'add') {
            $url = Url::toRoute(['tgstep/add', 'id' => $model->id]);
            return $url;
          } elseif ($action === 'view') {
            $url = Url::toRoute(['tgstep/view', 'id' => $model->id]);
            return $url;
          } elseif ($action === 'update') {
            $url = Url::toRoute(['tgstep/update', 'id' => $model->id]);
            return $url;
          } elseif ($action === 'delete') {
            $url = Url::toRoute(['tgstep/delete', 'id' => $model->id]);
            return $url;
          }
        }
      ],
    ]
]); */
?>